# ~/.bashrc

function cd {
        builtin cd "$@" && ls -F
}

# interactive prompt
PS1="[\u@\h:\w]\\$ "
# use the following instead, if you don't want your username in the prompt
#PS1="[\h:\w]\\$ "

# continuation interactive prompt (for multi-line commands)
PS2='> '

source ~/.bash_prompt

#function connect_ssh_agent() {
#  # set SSH_AUTH_SOCK env var to a fixed value
#  export SSH_AUTH_SOCK=~/.ssh/ssh-agent.sock
#  # test whether $SSH_AUTH_SOCK is valid
#  ssh-add -l 2>/dev/null >/dev/null
#  # if not valid, then start ssh-agent using $SSH_AUTH_SOCK
#  [ $? -ge 2 ] && ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
#}
